# Site settings
title: Sam Chester
subtitle: PhD Candidate
email: schester@ldeo.columbia.edu
description: Sam Chester
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://schester1.github.io" # the base hostname & protocol for your site
author:
street_address: ""
city: "New York City"
state: "NY"
zip_code: "01227"
country: "USA"
phone: ""

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://github.com/schester1
googleplus_url: 
instagram_url: https://www.instagram.com/samchestermusic/?hl=en
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 
google_scholar_url: https://scholar.google.com/citations?user=QDMQPFMAAAAJ&hl=en


# Build settings
markdown: kramdown
